import argparse
import uuid
from kg_export.json_to_csv import JsonToCsv
from kg_export.csv_to_json import CsvToJson
from kg_export.log.Logger import Logger

logger = Logger()

if __name__ == '__main__':
    request_id = str(uuid.uuid4())
    parser = argparse.ArgumentParser()
    print('\n\n New parse request with request_id - {}'.format(request_id))
    logger.info('\n\n New parse request with request_id - {}'.format(request_id))
    parser.add_argument('--input_file_path', help='path for input file')
    parser.add_argument('--type', help='types supported are json_to_csv and csv_to_json')
    parser.add_argument('--output_file_path', help='path for output file generated by ExportParser tool')
    input_arguments = parser.parse_args()
    args = dict()
    args['request_type'] = input_arguments.type
    args['input_file_path'] = input_arguments.input_file_path
    args['output_file_path'] = input_arguments.output_file_path
    if args.get('request_type', '').strip() == 'json_to_csv':
        parser = JsonToCsv()
        logger.info('Initiatated kg export json parsing')
        parser.parse(args['input_file_path'], args['output_file_path'])
    elif args.get('request_type', '').strip() == 'csv_to_json':
        parser = CsvToJson()
        parser.parse(args['input_file_path'], args['output_file_path'])
    else:
        print('invalid request_type - {}'.format(args.get('request_type', '')))